<?php
return [
    'adminEmail' => 'studio@redhex.pt',
    'supportEmail' => 'studio@redhex.pt',
    'user.passwordResetTokenExpire' => 3600,
    'dirs' => [
        'solutions' => [
            'back' => true,
            'module' => 'solution',
            'pid' => 0,
            'id' => 1,
            'icon' => 'pe-7s-star',
            'name' => 'Что вас беспокоит?',
        ],
        'articles' => [
            'back' => true,
            'module' => 'article',
            'pid' => 0,
            'id' => 23,
            'icon' => 'pe-7s-star',
            'name' => 'Статьи',
        ],
        'specialist' => [
            'back' => true,
            'module' => 'specialist',
            'pid' => 0,
            'id' => 23,
            'icon' => 'pe-7s-star',
            'name' => 'Специалисты',
        ],
        'news' => [
            'back' => true,
            'module' => 'news',
            'pid' => 0,
            'id' => 2,
            'icon' => 'pe-7s-star',
            'name' => 'Новости',
        ],
        /*'gallery' => [
            'back' => true,
            'module' => 'gallery',
            'pid' => 0,
            'id' => 4,
            'icon' => 'pe-7s-star',
            'name' => 'Слайдер Обо мне',
        ],*/
        'comments' => [
            'back' => true,
            'module' => 'comment',
            'pid' => 0,
            'id' => 5,
            'icon' => 'pe-7s-star',
            'name' => 'Отзывы',
        ],
        'faqs' => [
            'back' => true,
            'module' => 'faq',
            'pid' => 0,
            'id' => 6,
            'icon' => 'pe-7s-star',
            'name' => 'Вопрс-Ответ',
        ],
        'products' => [
            'back' => true,
            'module' => 'product',
            'pid' => 0,
            'id' => 3,
            'icon' => 'pe-7s-star',
            'name' => 'Наши продукты',
        ],
        'chat' => [
            'back' => true,
            'module' => 'chat',
            'pid' => 0,
            'id' => 21,
            'icon' => 'pe-7s-star',
            'name' => 'Чат',
        ],
        'seo' => [
            'back' => true,
            'module' => 'seo',
            'pid' => 0,
            'id' => 22,
            'icon' => 'pe-7s-star',
            'name' => 'SEO',
        ],
    ],
];